# Generated by Django 5.0.6 on 2024-06-17 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_category', '0003_alter_middlecategory_middle_image'),
        ('app_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_category.subcategory'),
        ),
    ]
