# Generated by Django 5.0.6 on 2024-06-20 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_service', '0002_service_category_id'),
        ('my_app', '0009_rename_is_admin_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='owner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='my_app.profilemodel'),
        ),
    ]
