# Generated by Django 5.0.6 on 2024-06-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneverification',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
