# Generated by Django 5.0.6 on 2024-06-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_user_groups_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
