# Generated by Django 5.0.6 on 2024-06-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_phoneverification_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverification',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
