# Generated by Django 5.0.6 on 2024-06-20 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'MainCategory',
                'verbose_name_plural': 'MainCategories',
                'db_table': 'main_category',
            },
        ),
        migrations.CreateModel(
            name='MiddleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(max_length=255)),
                ('middle_image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('main_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_category.maincategory')),
            ],
            options={
                'verbose_name': 'MiddleCategory',
                'verbose_name_plural': 'MiddleCategories',
                'db_table': 'middle_category',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=255)),
                ('main_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_category.maincategory')),
                ('middle_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_category.middlecategory')),
            ],
            options={
                'verbose_name': 'SubCategory',
                'verbose_name_plural': 'SubCategories',
                'db_table': 'sub_category',
            },
        ),
    ]
