# Generated by Django 5.0.6 on 2024-06-17 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name': 'MainCategory', 'verbose_name_plural': 'MainCategories'},
        ),
        migrations.AlterModelOptions(
            name='middlecategory',
            options={'verbose_name': 'MiddleCategory', 'verbose_name_plural': 'MiddleCategories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'SubCategory', 'verbose_name_plural': 'SubCategories'},
        ),
    ]
