# Generated by Django 5.0.6 on 2024-06-20 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQsModel',
            new_name='FAQModel',
        ),
    ]
