# Generated by Django 5.0.6 on 2024-06-19 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_service', '0002_service_category_id'),
        ('comment', '0003_service_alter_feedbackmodel_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='app_service.service'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
